name: build-and-release
on:
  push:
    tags: ['v*']
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g. v1.1.0)'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./src/QrDemoVB/QrDemoVB.vbproj

      - name: Publish single-file (win-x64, self-contained)
        shell: pwsh
        run: |
          dotnet publish ./src/QrDemoVB/QrDemoVB.vbproj -c Release -r win-x64 --self-contained true `
            -p:PublishSingleFile=true `
            -p:EnableCompressionInSingleFile=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -p:DebugType=None -p:DebugSymbols=false `
            -o ./artifacts/win-x64
          Compress-Archive -Path ./artifacts/win-x64/* -DestinationPath ./artifacts/QrDemoVB-win-x64.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || github.event.release.tag_name || inputs.tag }}
          files: artifacts/QrDemoVB-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
